"""Scenario and publication spine table writer adapters."""

from __future__ import annotations

from pathlib import Path

from ratewall.databook.table_io import write_rows


RATEWALL_WALL_HIT_SCENARIO_FIELDS = [
    "assumption_set",
    "description",
    "horizon",
    "mode",
    "policy_rate_bps",
    "public_impulse_multiplier",
    "public_impulse_multiplier_status",
    "public_debt_stock_scale",
    "debt_state_drag_multiplier",
    "treasury_repricing_speed_share",
    "rate_path_bps_year",
    "treasury_repricing_pass_through",
    "fed_liability_stock_scale",
    "iorb_pass_through_scale",
    "on_rrp_pass_through_scale",
    "current_remittance_timing_share",
    "future_remittance_drag_timing_share",
    "future_remittance_drag_treatment",
    "treasury_factor_multiplier",
    "iorb_factor_multiplier",
    "on_rrp_factor_multiplier",
    "remittance_current_factor_multiplier",
    "remittance_future_factor_multiplier",
    "treasury_interest_demand_share",
    "iorb_recipient_demand_share",
    "on_rrp_recipient_demand_share",
    "current_remittance_demand_share",
    "future_remittance_drag_demand_share",
    "fiscal_offset_share",
    "tga_liquidity_offset_share",
    "firm_cash_attenuation_share",
    "safe_asset_allocation_offset_share",
    "safe_asset_allocation_drag_share",
    "zero_interest_credit_attenuation_share",
    "firm_liquid_asset_stock_share_gdp",
    "zero_interest_credit_stock_share_gdp",
    "household_safe_asset_stock_share",
    "household_safe_asset_access_conditioner",
    "retail_safe_yield_pass_through_beta",
    "household_safe_yield_current_spend_share",
    "deposit_mmf_substitution_conditioner",
    "deposit_mmf_substitution_drag_share",
    "firm_liquid_asset_cushion_share",
    "firm_rollover_pressure_share",
    "foreign_treasury_holder_leakage_share",
    "interest_income_tax_timing_leakage_share",
    "rate_sensitive_consumer_credit_stock_share_gdp",
    "consumer_credit_reprice_beta",
    "consumer_credit_cashflow_drag_conversion",
    "cre_refi_drag_gdp_share_per_100bp_year",
    "private_credit_ndfi_credit_drag_share",
    "denominator_sidecar_overlap_discount_share",
    "fixed_mortgage_payment_shield_share_of_household_borrowing_drag",
    "pension_contribution_relief_gdp_share_per_100bp_year",
    "retirement_insurance_yield_spend_conversion_share",
    "pension_insurance_pass_through_lag_years",
    "gdp_bil",
    "treasury_interest_impulse_bil",
    "fed_interest_impulse_bil",
    "iorb_interest_impulse_bil",
    "on_rrp_interest_impulse_bil",
    "current_remittance_state_bil",
    "signed_current_remittance_impact_bil",
    "current_remittance_positive_support_bil",
    "current_remittance_negative_drag_bil",
    "current_remittance_reduction_bil",
    "future_remittance_drag_bil",
    "private_recipient_cashflow_impulse_bil",
    "component_display_public_impulse_total_bil",
    "current_treasury_remittance_gap_bil",
    "future_public_finance_drag_bil",
    "net_public_finance_adjustment_bil",
    "gross_public_interest_impulse_bil",
    "treasury_domestic_impulse_bil",
    "treasury_interest_demand_offset_bil",
    "iorb_demand_offset_bil",
    "on_rrp_demand_offset_bil",
    "current_remittance_demand_offset_bil",
    "future_remittance_drag_demand_offset_bil",
    "interest_demand_offset_bil",
    "absorber_basis",
    "fiscal_offset_bil",
    "tga_liquidity_offset_bil",
    "net_interest_before_fiscal_tga_offsets_bil",
    "net_interest_demand_offset_bil",
    "net_interest_after_fiscal_tga_offsets_bil",
    "firm_cash_yield_base_bil",
    "firm_cash_attenuation_bil",
    "firm_cash_applicable_drag_share",
    "domestic_safe_interest_impulse_bil",
    "safe_asset_allocation_offset_bil",
    "safe_asset_allocation_drag_bil",
    "zero_interest_credit_base_bil",
    "zero_interest_credit_attenuation_bil",
    "total_scaled_firm_cash_attenuation_bil",
    "total_scaled_zero_interest_credit_attenuation_bil",
    "household_safe_yield_capture_offset_bil",
    "baseline_safe_yield_access_share",
    "deposit_mmf_incremental_access_share",
    "deposit_mmf_substitution_offset_bil",
    "deposit_mmf_substitution_drag_bil",
    "total_scaled_deposit_mmf_substitution_drag_bil",
    "firm_liquid_asset_cushion_offset_bil",
    "total_scaled_firm_liquid_asset_cushion_offset_bil",
    "firm_rollover_pressure_drag_bil",
    "total_scaled_firm_rollover_pressure_drag_bil",
    "assumption_mode_promoted_offset_total_bil",
    "assumption_mode_promoted_drag_total_bil",
    "assumption_mode_promoted_net_effect_bil",
    "assumption_mode_promotion_status",
    "foreign_treasury_holder_leakage_drag_bil",
    "treasury_after_foreign_leakage_offset_bil",
    "interest_income_tax_timing_base_bil",
    "interest_income_tax_timing_drag_bil",
    "recipient_leakage_sidecar_drag_total_bil",
    "recipient_leakage_sidecar_countervailing_total_bil",
    "recipient_leakage_sidecar_offset_ratio",
    "consumer_credit_drag_sidecar_bil",
    "cre_refi_drag_sidecar_bil",
    "private_credit_ndfi_drag_sidecar_bil",
    "denominator_sidecar_positive_drag_total_bil",
    "denominator_sidecar_overlap_discount_bil",
    "denominator_sidecar_overlap_discount_status",
    "housing_lockin_payment_shield_sidecar_bil",
    "denominator_sidecar_drag_adjustment_bil",
    "denominator_sidecar_adjusted_conventional_drag_bil",
    "denominator_sidecar_offset_ratio",
    "pension_contribution_relief_sidecar_bil",
    "retirement_insurance_yield_spend_sidecar_bil",
    "pension_insurance_pass_through_lag_years_output",
    "assumption_mode_sidecar_status",
    "countervailing_total_bil",
    "scalar_countervailing_total_bil",
    "composition_only_countervailing_total_bil",
    "total_scaled_countervailing_total_bil",
    "targeted_attenuation_drag_basis",
    "scalar_baseline_uses_split_targeted_attenuation",
    "conventional_contractionary_anchor_bil",
    "conventional_contractionary_effect_bil",
    "borrowing_cost_drag_bil",
    "credit_supply_drag_bil",
    "asset_price_drag_bil",
    "expectations_drag_bil",
    "exchange_rate_external_drag_bil",
    "denominator_share_sum",
    "denominator_share_sum_status",
    "split_denominator_total_drag_multiplier",
    "split_denominator_mode",
    "composition_only_split_ratio",
    "total_scaled_split_ratio",
    "split_denominator_conventional_drag_bil",
    "ratewall_offset_ratio",
    "split_denominator_offset_ratio",
    "ratewall_offset_ratio_low_drag_sensitivity",
    "ratewall_offset_ratio_high_drag_sensitivity",
    "wall_hit_under_assumptions",
    "split_denominator_wall_hit_under_assumptions",
    "wall_classification",
    "split_denominator_wall_classification",
    "denominator_model_comparison",
    "classification_change_driver",
    "why_hit_or_nonhit",
    "decisive_margin_bil",
    "dominant_gross_interest_subchannel",
    "dominant_net_countervailing_channel",
    "dominant_countervailing_channel",
    "required_countervailing_for_hit_bil",
    "remaining_gap_to_wall_bil",
    "excess_over_wall_bil",
    "assumption_status",
    "source_status",
    "treasury_recipient_map_status",
    "iorb_recipient_map_status",
    "on_rrp_recipient_map_status",
    "current_remittance_capacity_status",
    "future_remittance_timing_status",
    "component_recipient_map_status",
    "claim_boundary",
    "empirical_claim_enabled",
    "policy_failure_claim_enabled",
    "pricing_output_enabled",
    "incidence_claim_enabled",
    "welfare_claim_enabled",
]


RATEWALL_MINIMUM_CONDITIONS_FIELDS = [
    "assumption_set",
    "condition_parameter",
    "condition_relation",
    "minimum_or_maximum_value_to_hit_wall",
    "frontier_status",
    "parameter_pack_low",
    "parameter_pack_base",
    "parameter_pack_high",
    "threshold_within_parameter_pack",
    "threshold_pack_status",
    "base_ratewall_offset_ratio",
    "claim_boundary",
]


RATEWALL_PAPER_CANONICAL_SCENARIO_RESULT_FIELDS = [
    "scenario_order",
    "ladder_step",
    "assumption_set",
    "ratewall_offset_ratio",
    "paper_regime",
    "wall_status",
    "dominant_driver",
    "dominant_component",
    "dominant_component_value_bil",
    "top_frontier_driver_parameter",
    "top_hit_fragility_parameter",
    "stacking_score",
    "effective_stack_score",
    "what_this_scenario_shows",
    "source_mode_label",
    "prior_narrowing_allowed",
    "formula_replacement_allowed",
    "main_offset_ratio_changed_this_tranche",
    "dynamic_equation_changed_this_tranche",
    "split_denominator_promotion_allowed",
    "empirical_claim_enabled",
    "policy_failure_claim_enabled",
    "pricing_output_enabled",
    "incidence_claim_enabled",
    "welfare_claim_enabled",
    "tax_output_enabled",
    "mpc_output_enabled",
    "holder_allocation_enabled",
    "reset_calendar_construction_enabled",
    "raw_rate_shock_enabled",
    "causal_financialization_claim_enabled",
    "claim_boundary",
]


PUBLICATION_CLAIM_DECISION_FIELDS = [
    "claim_id",
    "claim_layer",
    "publication_decision",
    "publication_claim_enabled",
    "promotion_claim_enabled",
    "evidence_artifact",
    "decision_basis",
    "required_label",
    "blocked_language",
    "claim_boundary",
]


def _write_ratewall_wall_hit_scenarios_table(
    path: Path, rows: list[dict[str, str]]
) -> None:
    write_rows(path, rows, RATEWALL_WALL_HIT_SCENARIO_FIELDS)


def _write_ratewall_minimum_conditions_to_hit_wall_table(
    path: Path, rows: list[dict[str, str]]
) -> None:
    write_rows(path, rows, RATEWALL_MINIMUM_CONDITIONS_FIELDS)


def _write_ratewall_paper_canonical_scenario_results_table(
    path: Path, rows: list[dict[str, str]]
) -> None:
    write_rows(path, rows, RATEWALL_PAPER_CANONICAL_SCENARIO_RESULT_FIELDS)


def _write_publication_claim_decision_table(
    path: Path, rows: list[dict[str, str]]
) -> None:
    write_rows(path, rows, PUBLICATION_CLAIM_DECISION_FIELDS)
